# Generated by Django 4.2.30 on 2026-05-24 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_patient_email_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='investigations/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist')], max_length=50),
        ),
    ]
