# Generated by Django 4.2.30 on 2026-09-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0003_investigation_file_user_user_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="insurance_covered_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bill",
            name="patient_payable_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurance_coverage_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurance_provider",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("pharmacist", "Pharmacist"),
                    ("receptionist", "Receptionist"),
                    ("patient", "Patient"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="hospital.branch",
            ),
        ),
    ]
